name: Build and Push Docker Image

# Запускаем конвейер только тогда, когда ты делаешь 'git push' в ветку main
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1. Копируем код твоего репозитория на виртуальную машину Гитхаба
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Логинимся в хранилище Гитхаба (используем встроенный секретный токен)
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # 3. Собираем образ по твоему Dockerfile и отправляем его в облако
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        # Называем образ по твоему нику и имени проекта
        tags: ghcr.io/${{ github.repository }}:latest